import fs from 'fs';
import path from 'path';
import { loadManifest, readComponent, stripPlaybookMetadata } from './cursor-export.mjs';

const GENERATED_BANNER =
  '<!-- Generated by celestial-ai-playbook. Source: {{source}}. Do not edit directly; edit src/roles instead. -->';

/** Minimal YAML frontmatter parser (no dependency). */
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) return { frontmatter: {}, body: content };

  const yaml = match[1];
  const body = content.slice(match[0].length);
  const frontmatter = {};

  for (const line of yaml.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const kv = trimmed.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;

    const [, key, raw] = kv;
    let value = raw.trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    } else if (value.startsWith('[') && value.endsWith(']')) {
      value = value
        .slice(1, -1)
        .split(',')
        .map((v) => v.trim().replace(/^["']|["']$/g, ''))
        .filter(Boolean);
    } else if (/^\d+$/.test(value)) {
      value = Number(value);
    } else if (value === 'true') value = true;
    else if (value === 'false') value = false;

    frontmatter[key] = value;
  }

  return { frontmatter, body };
}

function parseLegacyMetadata(body) {
  const triggers = [];
  const triggerMatch = body.match(/^@trigger\s+(.+)$/m);
  if (triggerMatch) {
    triggers.push(
      ...triggerMatch[1]
        .replace(/"/g, '')
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean)
    );
  }

  const priorityMatch = body.match(/^@priority\s+(\d+)$/m);
  const titleMatch = body.match(/^#\s+(?:ROLE:\s*)?(.+)$/m);

  return {
    triggers,
    priority: priorityMatch ? Number(priorityMatch[1]) : 50,
    title: titleMatch ? titleMatch[1].trim() : null,
  };
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function defaultCommand(name) {
  return `celestial-${name}`;
}

function defaultTitle(name) {
  return name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

/**
 * Normalize one role source file + manifest entry into a canonical role object.
 */
export function normalizeRole({ key, manifestConfig, content }) {
  const name = key.replace('roles/', '');
  const { frontmatter, body: rawBody } = parseFrontmatter(content);
  const legacy = parseLegacyMetadata(rawBody);
  const body = stripPlaybookMetadata(rawBody);

  const command =
    manifestConfig?.command ||
    frontmatter.command ||
    defaultCommand(name);

  const title =
    manifestConfig?.title ||
    frontmatter.title ||
    legacy.title ||
    defaultTitle(name);

  const triggers = Array.isArray(frontmatter.triggers)
    ? frontmatter.triggers
  : typeof frontmatter.triggers === 'string'
      ? frontmatter.triggers.split(',').map((t) => t.trim()).filter(Boolean)
      : legacy.triggers;

  const priority =
    manifestConfig?.priority ??
    frontmatter.priority ??
    legacy.priority ??
    50;

  const description =
    manifestConfig?.description ||
    frontmatter.description ||
    (triggers.length
      ? `Celestial Playbook role: ${title}. Use for ${triggers.slice(0, 6).join(', ')}.`
      : `Celestial Playbook role: ${title}.`);

  return {
    key,
    name,
    command,
    title,
    description,
    triggers,
    priority,
    body,
    source: `src/roles/${name}.md`,
    manifestConfig: manifestConfig || {},
  };
}

export function collectRoles(repoRoot, manifest) {
  const rolesDir = path.join(repoRoot, 'src', 'roles');
  if (!fs.existsSync(rolesDir)) return [];

  const files = fs
    .readdirSync(rolesDir)
    .filter((f) => f.endsWith('.md'))
    .sort();

  const roles = [];

  for (const file of files) {
    const name = file.replace(/\.md$/, '');
    const key = `roles/${name}`;
    const manifestConfig = manifest.components[key];

    if (manifestConfig && manifestConfig.type !== 'command') {
      throw new Error(
        `Manifest entry for ${key} must be type "command" (found "${manifestConfig.type}")`
      );
    }

    const content = readComponent(repoRoot, key);
    roles.push(
      normalizeRole({
        key,
        manifestConfig: manifestConfig || {
          type: 'command',
          command: defaultCommand(name),
          title: defaultTitle(name),
        },
        content,
      })
    );
  }

  return roles.sort((a, b) => b.priority - a.priority || a.name.localeCompare(b.name));
}

export function generatedBanner(role) {
  return GENERATED_BANNER.replace('{{source}}', role.source);
}

export function roleInstructionIntro(role) {
  return `Adopt the **${role.title}** persona for the current task. Follow dry-run protocols, mandatory checklists, and forbidden/required rules before changing code.`;
}
