/**
 * Synthesize — combine worker summaries into project-local rule file.
 */
import fs from 'fs';
import path from 'path';

const REQUIRED_SECTIONS = ['## Generated Rules'];

/**
 * Validate generated rule file structure before writing.
 */
export function validateRuleOutput(content) {
  const errors = [];
  if (!content.startsWith('---')) errors.push('MISSING_FRONTMATTER');
  if (!content.includes('alwaysApply:')) errors.push('MISSING_alwaysApply');
  for (const section of REQUIRED_SECTIONS) {
    if (!content.includes(section)) errors.push(`MISSING_SECTION:${section}`);
  }
  return { ok: errors.length === 0, errors };
}

/**
 * @param {string} projectDir
 * @param {Array<{ module: string, summary: string, ok: boolean }>} workerResults
 * @param {{ selectors: string[] }} meta
 */
export function synthesizeRules(projectDir, workerResults, meta = {}) {
  const absProject = path.resolve(projectDir);
  const outDir = path.join(absProject, '.cursor', 'rules');
  const outPath = path.join(outDir, 'celestial-generated.mdc');

  const sections = workerResults.map(w => {
    const label = w.module.replace(/\//g, ' > ').toUpperCase();
    const body = w.ok ? w.summary : `[${w.error}] ${w.summary}`;
    return `### ${label}\n\n${body}`;
  });

  const content = [
    '---',
    'alwaysApply: true',
    `description: "Celestial generated rules — selectors: ${(meta.selectors || []).join(', ')}"`,
    '---',
    '',
    '## Generated Rules',
    '',
    `> Auto-generated by \`ai-playbook generate-rules\`. Selectors: ${(meta.selectors || []).join(', ')}`,
    '',
    sections.join('\n\n---\n\n'),
    '',
  ].join('\n');

  const validation = validateRuleOutput(content);
  if (!validation.ok) {
    return { ok: false, errors: validation.errors, outPath: null };
  }

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outPath, content);

  return { ok: true, outPath, charCount: content.length, moduleCount: workerResults.length };
}
