#!/usr/bin/env node

/**
 * Role export — writes IDE-native command files.
 * Default: global install paths only (~/.cursor, ~/.claude, etc.)
 * Use --project <abs-path> for explicit project targeting (generate-rules workflow).
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { loadRoles, ROLE_SCHEMA } from './lib/load-roles.mjs';
import { resolveRoleOutputDir, cliResult } from './lib/global-paths.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

const VALID_TARGETS = Object.keys(ROLE_SCHEMA.defaults.targets);

const GENERATED_NOTICE =
  '<!-- AUTO-GENERATED by celestial-ai-playbook (export-roles). Do not edit; modify src/roles/ instead. -->';

function parseArgs(argv) {
  const opts = { targets: null, global: true, projectDir: null, homeDir: null };

  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--target' && argv[i + 1]) {
      opts.targets = argv[++i].split(',').map(t => t.trim());
    } else if (argv[i] === '--project' && argv[i + 1]) {
      opts.global = false;
      opts.projectDir = path.resolve(argv[++i]);
    } else if (argv[i] === '--global') {
      opts.global = true;
      opts.projectDir = null;
    } else if (argv[i] === '--home' && argv[i + 1]) {
      opts.homeDir = path.resolve(argv[++i]);
    }
  }

  return opts;
}

function resolveTargets(requested) {
  if (!requested) return [...VALID_TARGETS];
  const unknown = requested.filter(t => !VALID_TARGETS.includes(t));
  if (unknown.length) {
    console.error(`ERROR: Unknown target(s): ${unknown.join(', ')}`);
    console.error(`Valid targets: ${VALID_TARGETS.join(', ')}`);
    process.exit(1);
  }
  return requested;
}

function artifactFilename(target, role) {
  // Copilot & Antigravity personas are Skills: <command>/SKILL.md
  if (target === 'copilot' || target === 'antigravity') return path.join(role.command, 'SKILL.md');
  return `${role.command}.md`;
}

function instructionIntro(role) {
  return `Adopt the **${role.title}** persona for the current task. Follow dry-run protocols, mandatory checklists, and forbidden/required rules before changing code.`;
}

function renderCursor(role) {
  return [`# ${role.title}`, '', instructionIntro(role), '', '---', '', role.body, '', GENERATED_NOTICE].join('\n');
}

function renderClaude(role) {
  return [
    '---',
    `description: ${JSON.stringify(role.description)}`,
    'disable-model-invocation: true',
    '---',
    '',
    `# ${role.title}`,
    '',
    instructionIntro(role),
    '',
    '---',
    '',
    role.body,
    '',
    GENERATED_NOTICE,
  ].join('\n');
}

/**
 * Skill (SKILL.md) renderer shared by Copilot and Antigravity.
 * Requires name + a highly descriptive description for trigger-matching.
 */
function renderSkill(role) {
  const skillDescription =
    `${role.title} persona. ${role.description}. ` +
    `Trigger when the task involves ${role.title.toLowerCase()} responsibilities.`;
  return [
    '---',
    `name: ${role.command}`,
    `description: ${JSON.stringify(skillDescription)}`,
    '---',
    '',
    `# ${role.title}`,
    '',
    instructionIntro(role),
    '',
    '---',
    '',
    role.body,
    '',
    GENERATED_NOTICE,
  ].join('\n');
}

export function render(target, role) {
  switch (target) {
    case 'cursor': return renderCursor(role);
    case 'claude': return renderClaude(role);
    case 'copilot': return renderSkill(role);
    case 'antigravity': return renderSkill(role);
    default: throw new Error(`No renderer for target: ${target}`);
  }
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

export function exportTarget(target, roles, { global = true, projectDir = process.cwd(), homeDir = undefined } = {}) {
  const dir = resolveRoleOutputDir(target, { global, projectDir, homeDir });
  ensureDir(dir);

  const written = [];
  for (const role of roles) {
    if (!role.targets[target]?.enabled) continue;
    const filename = artifactFilename(target, role);
    const outPath = path.join(dir, filename);
    ensureDir(path.dirname(outPath));
    fs.writeFileSync(outPath, render(target, role));
    written.push({ role: role.name, command: role.command, filename, outPath });
  }

  return { target, dir, written, global };
}

/**
 * Export roles to IDE targets.
 * @param {{ targets?: string[], global?: boolean, projectDir?: string, homeDir?: string, repoRoot?: string }} opts
 */
export function exportRoles(opts = {}) {
  const repoRoot = opts.repoRoot || REPO_ROOT;
  const rolesDir = path.join(repoRoot, 'src', 'roles');
  const roles = loadRoles(rolesDir);
  const targets = resolveTargets(opts.targets || null);
  const exportOpts = {
    global: opts.global !== false,
    projectDir: opts.projectDir ? path.resolve(opts.projectDir) : process.cwd(),
    homeDir: opts.homeDir,
  };

  return targets.map(t => exportTarget(t, roles, exportOpts));
}

const TARGET_LABELS = {
  cursor: 'Cursor',
  claude: 'Claude Code',
  copilot: 'GitHub Copilot',
  antigravity: 'Antigravity',
};

function printSummary(results, { global, projectDir, homeDir }) {
  const dest = global ? (homeDir || process.env.HOME) : projectDir;
  console.log(`\n📋 Role Export Summary (${global ? 'global' : 'project'})`);
  console.log(`   Destination: ${dest}\n`);

  let total = 0;
  for (const { target, dir, written } of results) {
    console.log(`── ${TARGET_LABELS[target]} (${written.length}) ──`);
    console.log(`   ${dir}`);
    for (const item of written) {
      console.log(`     /${item.command} → ${item.filename}`);
    }
    total += written.length;
  }
  console.log(`\nOK: ${total} file(s) written across ${results.length} target(s).\n`);
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  const rolesDir = path.join(REPO_ROOT, 'src', 'roles');
  const roles = loadRoles(rolesDir);

  if (!roles.length) {
    process.exit(cliResult(false, 'No role files found under src/roles/'));
  }

  const targets = resolveTargets(opts.targets);
  const exportOpts = {
    global: opts.global,
    projectDir: opts.projectDir || process.cwd(),
    homeDir: opts.homeDir,
  };

  const results = targets.map(t => exportTarget(t, roles, exportOpts));
  printSummary(results, exportOpts);
  process.exit(0);
}

const isCli = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isCli) main();

export { loadRoles };
