#!/usr/bin/env node

/**
 * Role export entrypoint.
 *
 * Loads normalized roles via the frontmatter-based loader, dispatches to
 * per-target renderers, and writes IDE-native files into the repo root.
 *
 * Usage:
 *   node scripts/export-roles.mjs                     # all targets
 *   node scripts/export-roles.mjs --target cursor     # single target
 *   node scripts/export-roles.mjs --target claude,copilot
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { loadRoles, ROLE_SCHEMA } from './lib/load-roles.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

const VALID_TARGETS = Object.keys(ROLE_SCHEMA.defaults.targets);

const GENERATED_NOTICE =
  '<!-- AUTO-GENERATED by celestial-ai-playbook (export-roles). Do not edit; modify src/roles/ instead. -->';

// ── Argument parsing ────────────────────────────────────────────────

function parseArgs(argv) {
  const opts = { targets: null, projectDir: process.cwd() };

  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--target' && argv[i + 1]) {
      opts.targets = argv[++i].split(',').map(t => t.trim());
    } else if (argv[i] === '--project' && argv[i + 1]) {
      opts.projectDir = path.resolve(argv[++i]);
    }
  }

  return opts;
}

function resolveTargets(requested) {
  if (!requested) return [...VALID_TARGETS]; // export all

  const unknown = requested.filter(t => !VALID_TARGETS.includes(t));
  if (unknown.length) {
    console.error(`✗ Unknown target(s): ${unknown.join(', ')}`);
    console.error(`  Valid targets: ${VALID_TARGETS.join(', ')}`);
    process.exit(1);
  }
  return requested;
}

// ── Output path + filename resolution ───────────────────────────────

function outputDir(target, projectDir) {
  switch (target) {
    case 'cursor':      return path.join(projectDir, '.cursor', 'commands');
    case 'claude':      return path.join(projectDir, '.claude', 'commands');
    case 'copilot':     return path.join(projectDir, '.github', 'prompts');
    case 'antigravity': return path.join(projectDir, '.agent', 'presets');
    default: throw new Error(`Unknown target: ${target}`);
  }
}

function artifactFilename(target, role) {
  if (target === 'copilot') return `${role.command}.prompt.md`;
  return `${role.command}.md`;
}

// ── Per-target renderers ────────────────────────────────────────────

function instructionIntro(role) {
  return `Adopt the **${role.title}** persona for the current task. Follow dry-run protocols, mandatory checklists, and forbidden/required rules before changing code.`;
}

function renderCursor(role) {
  return [
    GENERATED_NOTICE,
    '',
    `# ${role.title}`,
    '',
    instructionIntro(role),
    '',
    '---',
    '',
    role.body,
  ].join('\n');
}

function renderClaude(role) {
  return [
    '---',
    `description: ${JSON.stringify(role.description)}`,
    'disable-model-invocation: true',
    '---',
    '',
    GENERATED_NOTICE,
    '',
    `# ${role.title}`,
    '',
    instructionIntro(role),
    '',
    '---',
    '',
    role.body,
  ].join('\n');
}

function renderCopilot(role) {
  return [
    '---',
    `description: ${JSON.stringify(role.description)}`,
    `name: ${role.command}`,
    'agent: agent',
    '---',
    '',
    GENERATED_NOTICE,
    '',
    `# ${role.title}`,
    '',
    instructionIntro(role),
    '',
    '---',
    '',
    role.body,
  ].join('\n');
}

function renderAntigravity(role) {
  return [
    '---',
    `name: ${role.command}`,
    `title: ${JSON.stringify(role.title)}`,
    `description: ${JSON.stringify(role.description)}`,
    'type: preset',
    '---',
    '',
    GENERATED_NOTICE,
    '',
    `# ${role.title}`,
    '',
    instructionIntro(role),
    '',
    '---',
    '',
    role.body,
  ].join('\n');
}

function render(target, role) {
  switch (target) {
    case 'cursor':      return renderCursor(role);
    case 'claude':      return renderClaude(role);
    case 'copilot':     return renderCopilot(role);
    case 'antigravity': return renderAntigravity(role);
    default: throw new Error(`No renderer for target: ${target}`);
  }
}

// ── Export logic ────────────────────────────────────────────────────

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function exportTarget(target, roles, projectDir) {
  const dir = outputDir(target, projectDir);
  ensureDir(dir);

  const written = [];
  for (const role of roles) {
    if (!role.targets[target]?.enabled) continue;

    const filename = artifactFilename(target, role);
    const outPath = path.join(dir, filename);
    const content = render(target, role);

    fs.writeFileSync(outPath, content);
    written.push({ role: role.name, command: role.command, filename, outPath });
  }

  return { target, dir, written };
}

// ── Summary ─────────────────────────────────────────────────────────

const TARGET_LABELS = {
  cursor:      'Cursor',
  claude:      'Claude Code',
  copilot:     'GitHub Copilot',
  antigravity: 'Antigravity',
};

function printSummary(results, projectDir) {
  console.log('\n📋 Celestial Playbook — Role Export Summary');
  console.log(`   Project: ${projectDir}\n`);

  let totalFiles = 0;

  for (const { target, dir, written } of results) {
    const label = TARGET_LABELS[target] || target;
    const relDir = path.relative(projectDir, dir);

    console.log(`── ${label} (${written.length} files) ──`);
    console.log(`   ${relDir}/`);
    for (const item of written) {
      console.log(`     /${item.command} → ${item.filename}`);
    }
    console.log('');
    totalFiles += written.length;
  }

  console.log(`✅ ${totalFiles} file(s) written across ${results.length} target(s).\n`);
}

// ── Main ────────────────────────────────────────────────────────────

function main() {
  const opts = parseArgs(process.argv.slice(2));
  const targets = resolveTargets(opts.targets);
  const rolesDir = path.join(REPO_ROOT, 'src', 'roles');
  const roles = loadRoles(rolesDir);
  const projectDir = opts.projectDir;

  if (!roles.length) {
    console.error('✗ No role files found under src/roles/');
    process.exit(1);
  }

  console.log(`Loaded ${roles.length} roles from src/roles/`);
  console.log(`Exporting to ${projectDir}`);

  const results = targets.map(t => exportTarget(t, roles, projectDir));
  printSummary(results, projectDir);
}

const isCli = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isCli) {
  main();
}

export { exportTarget, render, loadRoles };
